/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dynamics;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Suthar
 */
public class QuickReg extends javax.swing.JFrame {
String Add="D:/DyPass";

    /**
     * Creates new form QuickReg
     */
    public QuickReg() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usridlbl = new javax.swing.JLabel();
        usrid = new javax.swing.JTextField();
        usrmbllbl = new javax.swing.JLabel();
        usrmbl = new javax.swing.JTextField();
        otplbl = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New User Registration");

        usridlbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usridlbl.setText("User ID:");

        usrid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usridFocusLost(evt);
            }
        });
        usrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usridKeyPressed(evt);
            }
        });

        usrmbllbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usrmbllbl.setText("Mobile No:");

        usrmbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usrmblKeyPressed(evt);
            }
        });

        otplbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        otplbl.setText("OTP:");

        otp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otpKeyPressed(evt);
            }
        });

        submit.setText("Sumbit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(otplbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usridlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usrid, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancel)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(submit))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(usrmbllbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usrmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usridlbl)
                    .addComponent(usrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrmbllbl)
                    .addComponent(usrmbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otplbl)
                    .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(cancel)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(!usrid.getText().isEmpty()&&!usrmbl.getText().isEmpty()){
            otp.setVisible(true);
            otplbl.setVisible(true);
            usrid.setEditable(false);
            usrmbl.setEditable(false);
            if(!otp.getText().isEmpty()){
                //Move to setup the password
                if(true){//check whether OTP is correct or not
                try {
                        //PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(baseadd+"/userID.txt", true)));
                    dirCreate.mainn(Add, usrid.getText());
                        PrintWriter out = new PrintWriter(new OutputStreamWriter(new FileOutputStream(Add+"/"+usrid.getText()+"/profile.txt", true), "UTF-8"));
                        out.println(usrid.getText());
                        out.println(usrid.getText());//Default password
                        out.println(usrmbl.getText());
                        out.close();
                        } catch (IOException p) {
                            JLabel label = new JLabel("Current User Not Update!!! "+p);
                        label.setFont(new Font("Arial", Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.ERROR_MESSAGE);
                        //errmessage.mainn("User Not Added!!! Error0005", 400, 200);
                        }
                    new NP(usrid.getText()).setVisible(true);
                }
            }
        }else{
            System.out.println("Enter valid userid And Mobile Number");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       otp.setVisible(false);
            otplbl.setVisible(false);
            usrid.setEditable(true);
            usrmbl.setEditable(true);
            otplbl.setText("");
            usrid.setText("");
            usrmbl.setText("");
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usridFocusLost
        // check for existance of userid
        File fl = new File(Add+"/"+usrid.getText()+"/profile.txt");
        if(fl.exists()){
            System.out.println("User already for the id :"+usrid.getText());
            usrid.requestFocus();
        }
    }//GEN-LAST:event_usridFocusLost

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void usrmblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usrmblKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            otp.requestFocus();
        }
    }//GEN-LAST:event_usrmblKeyPressed

    private void usridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usridKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            usrmbl.requestFocus();
        }
    }//GEN-LAST:event_usridKeyPressed

    private void otpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otpKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            submit.doClick();
        }
    }//GEN-LAST:event_otpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField otp;
    private javax.swing.JLabel otplbl;
    private javax.swing.JButton submit;
    private javax.swing.JTextField usrid;
    private javax.swing.JLabel usridlbl;
    private javax.swing.JTextField usrmbl;
    private javax.swing.JLabel usrmbllbl;
    // End of variables declaration//GEN-END:variables
}
